apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datadog
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: datadog
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.1.10
    helm:
      releaseName: datadog
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
