apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
  annotations:
    argocd.argoproj.io/sync-wave: '1000'
spec:
  target:
    name: datadog-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /datadog-agent
